#ASP.NET Core

trigger:
- main

pool: 
    name: PROD-FACTORY
    demands: []

variables:
    buildConfiguraion: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
